'''
QUESTION:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

CORRECT ANSWER:

4613732
'''

def fibo(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return fibo(n-1) + fibo(n-2)

class MemoizeAndList:
    def __init__(self, f):
        self.f = f
        self.memo = {}
        self.total = 0
    def __call__(self, *args):
        if not args in self.memo:
            result = self.f(*args)
            if result % 2 == 0:
                self.total += result
            self.memo[args] = result
        return self.memo[args]

fibo = MemoizeAndList(fibo) 

x = 1
while fibo(x) <= 4000000:
    x += 1

fibo.total
